### ISSUE TITLE
i try run but show me error 

### ISSUE THREAD

**Issue by mshma** [enghamzasalem/whats-gpt-firebase#1]
hello thank you for all support 

when i try run 
node index.js 

show me this 

import pkg from "qrcode-terminal";
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by enghamzasalem** [comment]
`npm install qrcode-terminal`
