### ISSUE TITLE
[Bug]: npm i threw an error 

### ISSUE THREAD

**Issue by moHaHa** [enghamzasalem/whats-gpt-firebase#3]
I got this error after these steps 

1. clone the project 
2. run `npm i`

my env
 `node  v16.14.2` and `Windows 10`

preview 
```bash
PS C:\Users\Mohammad\source\moHaHa\whats-gpt-firebase> npm i
npm WARN deprecated puppeteer@13.7.0: < 19.4.0 is no longer supported
npm ERR! code 1
npm ERR! path C:\Users\Mohammad\source\moHaHa\whats-gpt-firebase\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r982053! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/982053/chrome-win.zip
npm ERR!     at C:\Users\Mohammad\source\moHaHa\whats-gpt-firebase\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:371:27
npm ERR!     at ClientRequest.requestCallback (C:\Users\Mohammad\source\moHaHa\whats-gpt-firebase\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:500:13)
npm ERR!     at Object.onceWrapper (node:events:646:26)
npm ERR!     at ClientRequest.emit (node:events:526:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:482:22)
npm ERR!     at TLSSocket.emit (node:events:526:28)
npm ERR!     at addChunk (node:internal/streams/readable:315:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohammad\AppData\Local\npm-cache\_logs\2023-06-21T18_40_21_619Z-debug-0.log
```

**Comment by moHaHa** [comment]
it seems that npm download something from this URL  `https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/982053/chrome-win.zip`

![image](https://github.com/enghamzasalem/whats-gpt-firebase/assets/72744132/afd349ca-9ab3-4f46-a18e-8367c1428397)


I'm in **Syria**, and as all know Syria is **blocked** from many services and this one included 

✅ **Solution**:  use **VPN**
